"""add rate limit counters

Revision ID: 418e42bdc908
Revises: 8b0ae605e5e7
Create Date: 2026-09-03 20:18:02.589990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418e42bdc908'
down_revision = '8b0ae605e5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('bucket', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.CheckConstraint('hits >= 0', name='ck_rate_limit_hits_non_negative'),
    sa.PrimaryKeyConstraint('bucket', 'window_start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
