"""customer accounts

Optional customer accounts alongside guest checkout, which is unchanged.

``orders.customer_id`` is nullable and stays that way: NULL means a guest
order, which remains the primary path and the majority of rows. RESTRICT
rather than CASCADE, because order history has to outlive the account that
placed it — a customer is deactivated, never deleted out from under their own
orders.

``token_blocklist`` gains a second nullable owner column so a customer's
revoked token has somewhere to live with a real foreign key behind it, rather
than being written into ``admin_id`` where it would point at an unrelated
administrator.

Foreign keys are named explicitly. Alembic's autogenerated version left them to
the database and then tried to drop them by ``None``, which fails.

Revision ID: 6779d007a458
Revises: 22b9a0739c5f
Create Date: 2026-09-09 19:04:07.915898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6779d007a458'
down_revision = '22b9a0739c5f'
branch_labels = None
depends_on = None

FK_ORDERS_CUSTOMER = "fk_orders_customer_id_customers"
FK_BLOCKLIST_CUSTOMER = "fk_token_blocklist_customer_id_customers"


def upgrade():
    op.create_table(
        'customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_login_count', sa.Integer(), nullable=False),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_customers_email'), ['email'], unique=True
        )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False
        )
        batch_op.create_foreign_key(
            FK_ORDERS_CUSTOMER, 'customers', ['customer_id'], ['id'], ondelete='RESTRICT'
        )

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            FK_BLOCKLIST_CUSTOMER, 'customers', ['customer_id'], ['id'], ondelete='CASCADE'
        )


def downgrade():
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_constraint(FK_BLOCKLIST_CUSTOMER, type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(FK_ORDERS_CUSTOMER, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
