"""add order confirmation token

Revision ID: 8b0ae605e5e7
Revises: faff73f468bc
Create Date: 2026-09-03 11:10:17.279767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0ae605e5e7'
down_revision = 'faff73f468bc'
branch_labels = None
depends_on = None


def upgrade():
    # Nullable first: any existing order row (dev seed data, or a real order
    # once this has shipped) has no value for a column that didn't exist a
    # moment ago, and NOT NULL would reject every one of them outright.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_token', sa.String(length=64), nullable=True))

    # Backfill a distinct token per existing row. md5() of the row's own id
    # plus the current transaction timestamp needs no extension (unlike
    # gen_random_bytes/pgcrypto) and is unique across a handful of rows, which
    # is all this backfill ever has to be — every future row gets a proper
    # secrets.token_urlsafe() from the application.
    op.execute(
        "UPDATE orders SET confirmation_token = md5(id::text || clock_timestamp()::text) "
        "WHERE confirmation_token IS NULL"
    )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('confirmation_token', existing_type=sa.String(length=64), nullable=False)
        batch_op.create_index(batch_op.f('ix_orders_confirmation_token'), ['confirmation_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_confirmation_token'))
        batch_op.drop_column('confirmation_token')

    # ### end Alembic commands ###
