"""product image public id

Revision ID: faff73f468bc
Revises: d6da79eaacc0
Create Date: 2026-09-02 23:27:59.681228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faff73f468bc'
down_revision = 'd6da79eaacc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_check_constraint('ck_product_images_has_a_source', 'public_id IS NOT NULL OR url IS NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint('ck_product_images_has_a_source', type_='check')
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
